### ISSUE TITLE
python  data_preprocess_CAP.py   IndexError: index 0 is out of bounds for axis 0 with size 0   how to fix it?

### ISSUE THREAD

**Issue by aspnetcs** [sjjjjjj2/CPHOSS_MFD#1]
root@28a9987b4662:/workspace/CPHOSS_MFD/ICDAR2021_MFD/tools# python  data_preprocess_CAP.py
We use 0 formulas
Of the 0 valid formulas (whose w/h >= min_w_h_ratio = 3 and is of type embedded)
Of the 3 formulas
Now start generating informations.
Traceback (most recent call last):
  File "data_preprocess_CAP.py", line 431, in <module>
    formulanumlst = converter.generate_and_save()
  File "data_preprocess_CAP.py", line 341, in generate_and_save
    new_bboxes_dct_lst,formulacounter = self.random_bbox(generated_image_id) if random_number < self.args.RandomRatio else self.regular_bbox(generated_image_id)
  File "data_preprocess_CAP.py", line 102, in random_bbox
    bid = self.random_order[self.boxcounter]
IndexError: index 0 is out of bounds for axis 0 with size 0
root@28a9987b4662:/workspace/CPHOSS_MFD/ICDAR2021_MFD/tools#

**Comment by sjjjjjj2** [comment]
As is printed out by the program, I think after the selection there are only 0 formulas whose w/h >= min_w_h_ratio and is of type embedded of the 3 formulas in the database. There should not only be 3 formulas in the database if the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD is executed correctly (or if in some folder there are only 3 formulas, then it is not enough for our preprocessing and you may not use it). Please make sure that you first follow the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, and correctly set the --img_path   --org_json_path --dst_img_path  --dst_json_path arguements in data_preprocess_CAP.py. (They corresponds to the image folder for the original dataset, the json file for the original dataset generated by the preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, the destination folder for our generated dataset and the destination json file for our generated dataset.)

**Comment by aspnetcs** [comment]
Are you Chinese？可以用汉语交流吗？










--




At 2023-07-21 10:27:23, "ShiJZ" ***@***.***> wrote:

As is printed out by the program, I think after the selection there are only 0 formulas whose w/h >= min_w_h_ratio and is of type embedded of the 3 formulas in the database. There should not only be 3 formulas in the database if the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD is executed correctly (or if in some folder there are only 3 formulas, then it is not enough for our preprocessing and you may not use it). Please make sure that you first follow the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, and correctly set the --img_path --org_json_path --dst_img_path --dst_json_path arguements in data_preprocess_CAP.py. (They corresponds to the image folder for the original dataset, the json file for the original dataset generated by the preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, the destination folder for our generated dataset and the destination json file for our generated dataset.)

**Comment by aspnetcs** [comment]
你的联系方式发给我，帮我解决问题，给你报酬













--




At 2023-07-21 10:27:23, "ShiJZ" ***@***.***> wrote:

As is printed out by the program, I think after the selection there are only 0 formulas whose w/h >= min_w_h_ratio and is of type embedded of the 3 formulas in the database. There should not only be 3 formulas in the database if the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD is executed correctly (or if in some folder there are only 3 formulas, then it is not enough for our preprocessing and you may not use it). Please make sure that you first follow the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, and correctly set the --img_path --org_json_path --dst_img_path --dst_json_path arguements in data_preprocess_CAP.py. (They corresponds to the image folder for the original dataset, the json file for the original dataset generated by the preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, the destination folder for our generated dataset and the destination json file for our generated dataset.)

**Comment by sjjjjjj2** [comment]
Hello，这是我的邮箱。
这个repo并没有bug，您可以再检查一下自己的设置问题。

发件人: aspnetcs
发送时间: 2023年7月21日 15:28
收件人: sjjjjjj2/CPHOSS_MFD
抄送: ShiJZ; Comment
主题: Re: [sjjjjjj2/CPHOSS_MFD] python data_preprocess_CAP.py IndexError: index 0 is out of bounds for axis 0 with size 0 how to fix it?(Issue #1)

你的联系方式发给我，帮我解决问题，给你报酬













--




At 2023-07-21 10:27:23, "ShiJZ" ***@***.***> wrote:

As is printed out by the program, I think after the selection there are only 0 formulas whose w/h >= min_w_h_ratio and is of type embedded of the 3 formulas in the database. There should not only be 3 formulas in the database if the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD is executed correctly (or if in some folder there are only 3 formulas, then it is not enough for our preprocessing and you may not use it). Please make sure that you first follow the data preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, and correctly set the --img_path --org_json_path --dst_img_path --dst_json_path arguements in data_preprocess_CAP.py. (They corresponds to the image folder for the original dataset, the json file for the original dataset generated by the preprocessing process in https://github.com/Yuxiang1995/ICDAR2021_MFD, the destination folder for our generated dataset and the destination json file for our generated dataset.)

**Comment by sjjjjjj2** [comment]
这个repo并没有bug，您可以再检查一下您的设置问题。

**Comment by sjjjjjj2** [comment]
您可以通过邮箱联系我：shi-jz21@mails.tsinghua.edu.cn，不用收取报酬。
